- class/dashboard.class.php
- dashboard.php
- langs/en_US/query.lang
- langs/fr_FR/query.lang
- script/create-maj-base.php
Bonjour ATM Consulting,
Tout d'abord, bravo pour votre module, il est vraiment bien, et merci également pour la libération du code.
Voici une maigre contribution, qui j'espère en appellera d'autres.
Cela rajoute une option dans un dashboard "Rafraîchissement automatique du dashboard (minutes)", qui permet comme son nom l'indique, le rafraîchissement automatique du dashbard (eh oui!) lorsqu'on le consulte depuis la page "query/dashboard.php?action=run&uid=XXXXX".
Dolibarrement,
François.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/3)
> Add auto-refresh dashboard option

- class/query.class.php
- config.default.php
- js/query.js
- langs/fr_FR/query.lang
- query.php
Ajout la gestion des sommes intermédiaire
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/1)
> New group sum

- class/query.class.php
- js/query.js
- query.php
- script/interface.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/6)
> New add get lib status

- class/query.class.php
- js/query.js
- langs/fr_FR/query.lang
- query.php
- script/interface.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/7)
> NEW allow to search also on NULL

- class/query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/8)
> FIX where to having on group function

- class/query.class.php
- langs/fr_FR/query.lang
- query.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/9)
> NEW add button to switch

- js/query.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/10)
> FIX : table empty

- class/query.class.php
- js/query.js
+ little fix eval
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/11)
> FIX it because it's really more simple without bind

- core/modules/modquery.class.php
- langs/fr_FR/query.lang
- query.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/12)
> New import export query

- class/query.class.php
- config.default.php
- get-json.php
- langs/fr_FR/query.lang
- query.php
FIX load return
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/13)
> NEW export as JSON query with parameter

- bdd.php
- class/bddconnector.class.php
- class/query.class.php
- core/modules/modquery.class.php
- get-json.php
- js/query.js
- langs/fr_FR/query.lang
- query.php
- script/create-maj-base.php
- script/interface.php
- tpl/bdd.html
- Allow to create a database connector
- Allow to create query on other database
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/14)
> NEW database connector

- query.php
Fix export requete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/15)
> Fix export requete

- class/query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/16)
> NEW expert mode 2 allow GETPOST inclusion

- script/create-maj-base.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/17)
> Fix manque une virgule sur de l'insert

- class/query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/18)
> Fix ajout de l'entrée menu gauche des factures clients

- class/query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/20)
> NEW : add getNomURL on actioncomm

- class/query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/21)
> FIX: avoid php warnings about compatible class declaration

- class/query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/22)
> FIX: missing WHERE that messes dashboards up

- class/query.class.php
- langs/fr_FR/query.lang
Add supplier invoice into fields view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/23)
> Add supplier invoice into fields view

- class/query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/25)
> Ajout des variables {entity} et {userid} utilisable dans les requêtes

- class/query.class.php
- langs/en_US/query.lang
- langs/fr_FR/query.lang
- lib/query.lib.php
- query.php
- query_rights.php
- script/create-maj-base.php
Permet de définir sur une requête les groupes et/ou utilisateurs qui ont le droit d'y accéder.
La liste des requêtes affiche les requêtes autorisées
- à l'utilisateur connecté
- ou à un de ses groupes
- ou à personne en particulier (requête "publique")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/27)
> New query rights

- class/actions_query.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/29)
> FIX: homepage dashboard: Dolibarr 6.0+ compatibility

- core/modules/modquery.class.php
- dashboard.php
- langs/fr_FR/query.lang
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_query/30)
> NEW rights to see all dashboard

- query.php
When you are on the list of queries, you cannot change the number of elements shown on a page.
Cf. standard pagination mechanisms in abricot
> tk11407 - FIX 1.0 - pagination in Listview [abricot]

- ChangeLog.md
- class/query.class.php
- core/modules/modquery.class.php
> change titre to title

- ChangeLog.md
- admin/query_setup.php
- bdd.php
- class/query.class.php
- core/modules/modquery.class.php
- dashboard.php
- download-dashboard.php
- get-json.php
- menu.php
- query.php
- query_rights.php
- script/interface.php
> Fix 13.0 getpost

- ChangeLog.md
- admin/query_about.php
- class/techatm.class.php
- core/modules/modquery.class.php
NEW : Add about page with techAtm class
> NEW : Add about page with techAtm class
